# Generated by Django 5.0.3 on 2024-03-23 03:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('player_id', models.BigIntegerField()),
                ('name', models.CharField(max_length=255)),
                ('pos', models.CharField(max_length=8)),
            ],
            options={
                'ordering': ['player_id'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('season_id', models.BigIntegerField()),
                ('year', models.PositiveBigIntegerField()),
            ],
            options={
                'ordering': ['season_id'],
            },
        ),
        migrations.CreateModel(
            name='PlayerSeasonStat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stat_id', models.BigIntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.player')),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='employees.season')),
            ],
        ),
    ]
